; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24210.0 

	TITLE	F:\work\pack\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?b@@3PAHA					; b
_DATA	SEGMENT
?b@@3PAHA DD	01H					; b
	ORG $+39996
_DATA	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File f:\work\pack\main.cpp
; Line 3
	push	ebp
	mov	ebp, esp
; Line 4
	xor	eax, eax
; Line 5
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
